CREATE TABLE "movies" (
  "movie_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "title" varchar,
  "duration_mins" int,
  "imdb_id" int
);

CREATE TABLE "halls" (
  "hall_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "name" varchar,
  "regular_seats" integer,
  "vip_seats" integer
);

CREATE TABLE "timetable" (
  "timetable_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp,
  "start_dt" timestamp,
  "end_dt" timestamp,
  "movie_id" integer,
  "hall_id" integer,
  "regular_price" number,
  "vip_price" number
);

CREATE TABLE "tickets" (
  "ticket_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_number" integer,
  "timetable_id" int,
  "seat" int,
  "row" int,
  "price" decimal(6,2),
  "discount_id" int,
  "created_at" timestamp
);

ALTER TABLE "tickets" ADD FOREIGN KEY ("timetable_id") REFERENCES "timetable" ("timetable_id");

ALTER TABLE "timetable" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("movie_id");

ALTER TABLE "timetable" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("hall_id");
